CREATE FULLTEXT CATALOG [media_catalog] WITH ACCENT_SENSITIVITY = ON
GO
CREATE FULLTEXT INDEX ON [dbo].[media] KEY INDEX [PK_media_id] ON ([media_catalog]) WITH (CHANGE_TRACKING AUTO)
GO
ALTER FULLTEXT INDEX ON [dbo].[media] ADD ([title])
GO
ALTER FULLTEXT INDEX ON [dbo].[media] ENABLE
GO
