CREATE FULLTEXT CATALOG vw_media_catalog WITH ACCENT_SENSITIVITY = ON
GO
CREATE FULLTEXT INDEX ON vw_media KEY INDEX IDX_vw_media_id ON (vw_media_catalog) WITH (CHANGE_TRACKING AUTO)
GO
ALTER FULLTEXT INDEX ON vw_media ADD ([title])
GO
ALTER FULLTEXT INDEX ON vw_media ADD (search_terms)
GO
ALTER FULLTEXT INDEX ON vw_media ENABLE
GO
